# Generated by Django 4.2.13 on 2024-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainPicAlt',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
