# Generated by Django 4.2.13 on 2024-09-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_mainpicalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainPic',
            field=models.ImageField(null=True, upload_to='images/posts'),
        ),
    ]
