# Generated by Django 4.2.13 on 2024-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_mainpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mainPic_base64',
        ),
        migrations.AlterField(
            model_name='post',
            name='mainPic',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
