# Generated by Django 4.2.13 on 2024-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('category', models.IntegerField()),
                ('status', models.IntegerField()),
                ('keyWords', models.CharField(max_length=330)),
                ('summary', models.CharField(max_length=1000)),
                ('mainPic_base64', models.TextField()),
                ('body_html', models.TextField()),
                ('releaseType', models.IntegerField()),
                ('author_userName', models.CharField(max_length=100)),
            ],
        ),
    ]
