# Generated by Django 4.2.13 on 2024-06-14 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digitalProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
