# Generated by Django 4.2.13 on 2024-08-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalProducts', '0002_digitalproduct_created_at_digitalproduct_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='mainPicAlt',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='productLink',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
