# Generated by Django 4.2.13 on 2024-10-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalProducts', '0004_remove_digitalproduct_mainpic_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
