# Generated by Django 4.2.13 on 2024-11-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalProducts', '0005_digitalproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='digital-products/thumbnails/'),
        ),
    ]
