# Generated by Django 4.2.13 on 2025-01-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dPCategories', '0003_alter_dpcategory_name_alter_dpcategory_parent'),
        ('digitalProducts', '0006_digitalproduct_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dPCategories.dpcategory'),
        ),
    ]
