# Generated by Django 4.2.13 on 2025-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalProducts', '0009_digitalproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproduct',
            name='status',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
