# Generated by Django 4.2.13 on 2024-06-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dPCategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dPCategories.dpcategory'),
        ),
    ]
