# Generated by Django 4.2.13 on 2025-01-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dPCategories', '0002_alter_dpcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dpcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dPCategories.dpcategory'),
        ),
    ]
