# Generated by Django 4.2.13 on 2024-10-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessInfo', '0002_businessinfo_banner1_businessinfo_banner2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='Banner1Link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner1Text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner2Link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner2Text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner3Link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner3Text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='mainBannerLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='mainBannerText',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
