# Generated by Django 4.2.13 on 2024-10-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessInfo', '0003_businessinfo_banner1link_businessinfo_banner1text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='Banner4',
            field=models.ImageField(blank=True, null=True, upload_to='business/'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner4Link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner4Text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner5',
            field=models.ImageField(blank=True, null=True, upload_to='business/'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner5Link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='Banner5Text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
