# Generated by Django 4.2.13 on 2024-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessInfo', '0005_businessinfo_instagram_businessinfo_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='address2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
