# Generated by Django 4.2.13 on 2024-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessInfo', '0006_businessinfo_address2_alter_businessinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='tel2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
